[package]
name = "narinfo"
version = "0.1.0"
edition = "2018"
authors = [ "Graham Christensen <graham@grahamc.com>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
